package com.Madhatter.MadHatter.Repositories;

import com.Madhatter.MadHatter.models.Bootcamp;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 03/12/2018
*/
@Repository
public interface BootcampRepository extends JpaRepository<Bootcamp, Long> {
	@Query("select b from Bootcamp b")
	public List<Bootcamp> getAllBootcamp();
}
